server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # System logs
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*.log

  # Docker container logs
  - job_name: containers
    pipeline_stages:
      - json:
          expressions:
            stream: stream
            container_name: container_name
            log: log
      - labels:
          container_name:
      - output:
          source: log
    static_configs:
      - targets:
          - localhost
        labels:
          job: container_logs
          __path__: /var/lib/docker/containers/*/*-json.log

  # Application logs (adjust paths as needed)
  - job_name: app
    static_configs:
      - targets:
          - localhost
        labels:
          job: cai_platform
          __path__: /var/log/cai-platform/*.log
          environment: development
    pipeline_stages:
      - json:
          output: log
          source: log
      - labels:
          level:
          service:
      - output:
          source: log
