global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Alert manager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: []

# Rule files
rule_files:
  - 'alert.rules'

# Scrape configurations
scrape_configs:
  # CAI Platform API
  - job_name: 'cai-platform'
    scrape_interval: 10s
    metrics_path: '/api/stats'
    params:
      format: ['prometheus']
    static_configs:
      - targets: ['host.docker.internal:3001']  # Update with your API host and port
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: host.docker.internal:3001  # Update with your API host and port

  # Node Exporter
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # cAdvisor
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
